### ISSUE TITLE
Crab Claw Push/Pull continues when raycast no longer hits target

### ISSUE THREAD

**Issue by Mavodeli** [Mavodeli/spaceroguelite#101]

**Comment by Mavodeli** [comment]
TIL: "closes" doesn't cause the bot to auto-close an issue. 

Incidentally the issue should remain open.

The range check solves some funky behavior, but you can still move the mouse away from the targeted object to continue draining mana and playing the sound. The object, rightfully so, does not get moved anymore.

**Comment by Mavodeli** [comment]
Edit: Didn't merge changes into main yet, obviously it remains open🤦‍♂️

**Comment by KarylReyne** [comment]
> The range check solves some funky behavior, but you can still move the mouse away from the targeted object to continue draining mana and playing the sound. The object, rightfully so, does not get moved anymore.

We could just frame that as a conscious game design decision: the player should get punished if they are too incompetent to aim the ability at an object...
