### ISSUE TITLE
 Enemy Combat Behaviour

### ISSUE THREAD

**Issue by KarylReyne** [Mavodeli/spaceroguelite#21]
### Enemy Combat Behaviour
- [x] Base class
- [ ] Behaviour: moray eel (Lasse)
- [x] Behaviour: angler fish (Marcel)
- [x] Behaviour: puffer fish (Niklas - Optimization)
- [x] Behaviour: mantis shrimp (Niklas)
- [x] Added Sprite flip to Enemy class

**Comment by KarylReyne** [comment]
### Enemies Overview
- Moray eel: fast moving enemies, shoots debuff/paralysing projectile
- Anglerfish: can pull the player towards them with their luminescent fin ray and deals continuous damage by biting
- Puffer fish: small, nimble, damages with spikes (melee range)
- Mantis shrimp: hard shell, can shoot his two arms (throwing spear) at the player, cooldown to regrow arms, high dmg, high hp, also known as ‘shotgun shrimp’

**Comment by EmptyN8** [comment]
Add Sprite Flip to Enemy class 

- [ ]
