### ISSUE TITLE
Demo Gameplay (3 people)

### ISSUE THREAD

**Issue by Mavodeli** [Mavodeli/spaceroguelite#3]
- [x] Movement
- [x] Dash
- [x] Push/pull
- [ ] Upgrades
    - [x] Attract two items
    - [x] Infuse Item with negative charge
    - [ ] Claw crush
- [ ] health system
- [x] camera follow

Refactoring:
- [x] Change everything to 2D colliders/rigidbodies
- [ ] Change everything to `AddForce` or make it work together

**Comment by KarylReyne** [comment]
17.11.22, 20:00 Uhr

**Comment by xeniawetzel** [comment]
Implementierung angepeilt bis zum 27.11.2022
