### ISSUE TITLE
Misc. Sound Effects

### ISSUE THREAD

**Issue by KarylReyne** [Mavodeli/spaceroguelite#40]

**Comment by RicoKiwi** [comment]
WORLD INTERACTION
pickup item -c
pickup ult -c
enter spaceship -c
dash -c
pull/push objects
kill enemy
mana empty
get damaged
(button clicks)
repair sounds

INVENTORY
get message -c

AMBIENCE/STORY
background music?
enemy aggressive music?
spaceship flight
repair objects
electro asteroid?
ambient sound -12
