### ISSUE TITLE
come up with skills/upgrades

### ISSUE THREAD

**Issue by Mavodeli** [Mavodeli/spaceroguelite#5]

**Comment by RicoKiwi** [comment]
Maybe a skill to add gravity to certain objects, to attract enemies which will render them useless

**Comment by KarylReyne** [comment]
I mapped the already existing ideas to [these enemy types](https://github.com/Mavodeli/spaceroguelite/issues/4#issuecomment-1308693879)

#### Claw Melee
pull enemy towards you and crush them with the claw
- vulnerable: Octopus, but useful against most enemies
- resistant: Red lionfish

#### Just Kiss Them Already
ranged attack, pull two enemies towards each other (the name may not fit our setting, its a reference to [this visual novel](https://ekkoberry.itch.io/just-kiss-him-already))
- vulnerable: anything that gets pulled towards a Red lionfish
- resistant: Mantis shrimp

**Comment by KarylReyne** [comment]
### Skills Overview
#### Basics
- LC: attract objects, RC: push objects away, Click Both: hold object in place
#### Ultimate (upgradable)
- Crash two objects via mutual gravitational attraction (in space?)
- infuse a specific object with negative gravity pushing surrounding mobs/objects away (in research facility?)
- Crush mobs and objects like locks with your claw (in the wreck?)
place upgrades before a specific puzzle to teach about them
