### ISSUE TITLE
Sublevel: Abandoned Spaceship 2D Art

### ISSUE THREAD

**Issue by KarylReyne** [Mavodeli/spaceroguelite#54]
- [x] podest
- [x] laser beams
- [x] metal plate
- [x] gravity switch/button
- [x] glass wall
- [x] cure (yellow bio hazard box)
- [x] cargo container
- [x] icon for a 'Silicone' item (idk, a tube or just a heap of black goo)
- [x] redesign ultimate sprite for the crush ultimate -> (make it "cloudier")
- [x] 2x sprite for the emergency door: 1x open, 1x closed
- [x] Emergency door
- [x] hyperdrive core
- [x] chair/table (laboratory)
- [x] glass wall, broken version

**Comment by KarylReyne** [comment]
we need 2 sprites for the emergency door ;)

**Comment by DerSandmanHD** [comment]
everything done
