### ISSUE TITLE
level ideas

### ISSUE THREAD

**Issue by Mavodeli** [Mavodeli/spaceroguelite#6]

**Comment by Mavodeli** [comment]
Escape the charged nebula as first level/ segment
[https://youtu.be/oYeLwy5yQ-8](url)

**Comment by KarylReyne** [comment]
- planet surface/research lab (+gravity)
- inside a large asteroid (+different polarity centers in different wall segments bc of ore veins)
- space, but with a black hole that attracts a desired object (for a timer mechanic, but you can also throw enemies in the hole ;) )

**Comment by RicoKiwi** [comment]
Level in a different (maybe abandoned / by parasited occupied) spaceship

**Comment by bigatake108** [comment]
Local planets, space ships and asteroid-fields are unlockable and reachable via an EVA-Pod-like motorized escape pod. 
The player has to explore these environments, as they bare the necessary ressources needed for reparing the ship. They might will find a sort-of "starship scrapyard" to hunt for specific parts, or take what's needed from somebody elses functioning ship (stealing;D). 

Unpleasantly, the protagonist has to leave their ship unattended. Therefore they can't stay in distant regions for to long, otherwise parts might be stolen from their ship!

**Comment by Mavodeli** [comment]
for room based levels the camera snaps to the room (for large rooms it is bound to the room, but follows the player)

**Comment by KarylReyne** [comment]
###Spaceship hub
#### Interaction points
- upgrade/med station
- hyperdrive/fuel intake/etc (where the player can deposit collected items)
- window that can be closed/opened

**Comment by KarylReyne** [comment]
### Tablet
opens inside the active scene (e.g. skyrim)
- inventory
- mail inbox
- (installed upgrades/infection status/...)

**Comment by KarylReyne** [comment]
### Levels Overview
- Hub: Own spaceship
- space level (charged nebula?) (360° exploration)
- scavenge wrecked spaceship(-s) (haunted homestead of the 30%-opacity fishies and a rogue AI), rogue AI controls gravity in some parts (2 directional exploration - hyperdrive parts <-> emergency meds + upgrade?)
- research facility on planet surface (1 directional exploration, retrace final path to helipad after finding the cure)

**Comment by KarylReyne** [comment]
### Story: Hub
- Sent to find a cure for our colony
- Our ship was damaged during a hyperjump by a charged nebula
- We wake up from cryostasis and notice the crabasite
- We need to take care of immediate repairs
- The board computer tells us about all the systems, because we suffer from amnesia

**Comment by KarylReyne** [comment]
### Story: Space Level
- We need to collect resources to repair our basic thrusters to leave the nebula
- Additionally we need to repair our small landing ship
- The player learns how to use the push/pull mechanic without gravity here

**Comment by KarylReyne** [comment]
### Story: Wrecked Spaceship
- Controlled by rogue AI
- Already killed aliens are enemies (transparent fishies)
- Rogue AI wants to kill us too -> (dangerous) puzzles
- contains what we need to repair the hyper drive

**Comment by KarylReyne** [comment]
### Story: Research Facility
- has the cure
- scanner broken → land nearby and search for it
- research on the parasites, they broke free and roam the lab
- landing spots/ helipad to bring landing ship closer as you explore

**Comment by KarylReyne** [comment]
### Story: Hub
idea for 'immediate repairs': player has to re-enable the gravity on the ship (simply float towards a button and press it)
