### ISSUE TITLE
story snippets and ideas

### ISSUE THREAD

**Issue by Mavodeli** [Mavodeli/spaceroguelite#7]

**Comment by Mavodeli** [comment]
We were in hydro-/cryostasis and our ship ran into a charged nebula, we need to escape it before we sustain any more damage than we already have. We also notice that a parasite has taken hold in our [left/right] arm. Let's worry about that when our ship is safe...

**Comment by KarylReyne** [comment]
**protagonist:** freelance explorer/mercenary
**contractor:** small remote colony of the [arbitrary intergalactic empire] that's running low on manpower 'cause of a strange pandemic.
**task:** find a cure
**the disease:** infected reported extreme muscle/joint pain, headache (and are thus unable to work efficiently, which is the crucial point for the colony administration) and occasional involuntary limb movements (also contributes to the work inability). they dont know its a parasite, for them its 'just a nuisance' that's affecting their productivity

### story ideas
    - you actually manage to find a cure. but the sample is so small that you can only either use it to save the colony (they would use the sample as cultivation starter) or yourself (the disease/parasite has already spread so much that it will kill you before the colony manages to sufficiently multiply the sample)
    - according to wikipedia, crabs use their claws for communication. we could reflect that: claw 'communicates' with the player/protagonist, e.g. by snapping frequently/glowing/whatever whenever enemies are in the immediate vicinity ((like sting in lotr/the voices in hellblade) once the player is conditioned to rely on the snapping that may be used as false alarm later down the line when the infection gets worse (as part of the 'alter gameplay with infection progression'-idea))

### storytelling
    - inform about mission via star-wars-text roll (kinda lame but easy to implement and still cool in a nerdy way)
    - inform about mission via mission-briefing mail on the board computer
        - could use the board computer mail in-box for more storytelling: the colony admin. updates you on how the infection progresses ("please hurry, today one of the miners killed their co-worker by ripping their throat out with that claw-thing" - stuff like that)

**Comment by RicoKiwi** [comment]
See the "stargazer" name for some story telling idea

**Comment by GreenICow** [comment]
STORY

Prolog: (Womöglich durch einen Comic-Band realisierbar)

Der Hauptcharacter (du) schippert auf entspannt durchs All, als auf einmal das Schiff kaputt geht (wie? warum?). Die Lichter werden Rot, die Alarmanlage blinkt. Im nächsten Moment wird einem Schwarz
vor Augen. Als man aufwacht, glimmt nur noch das Lämpchen des Notstromaggregates schwach in der Dunkelheit. 
Als sich deine Augen langsam an die Dunkelheit gewöhnen, schimmert etwas ungewöhnlich Rot durch die Reflektion des Lämpchens in deinem Augenwinkel. Sofort bist du hellwach! Ein stechender Schmerz
durchzuckt deinen rechten Arm, der sich schwer und heiß anfühlt. Du fährst hoch und betätigst den Lichtschalter. -Ende des Prologs- 

Lvl 1: 		Ort: Raumschiff, Weltall 

Erkenntnisse:   - Du realiserst den Parasiten an deinem Arm ( kann der Charakter sprechen? ) 
		- Das Schiff ist kaputt, die Rettungskapsel intakt. Jedoch fehlt Treibstoff/Energie.
		- Der Scanner/Sprachassistent des Raumschiffes zeigt ein zur Reparatur essentielles Bauteil in einer Forschungsstation auf einem nahe gelegenen Planeten.

  -> somit muss man das Schiff verlassen, um Rohstoffe für den Energiegenerator zu sammeln.

		- Lebewesen aus dem All fühlen sich gestört, und greifen dich an (Spezies einfügen)

  -> man findet heraus, dass einem der Arm auch nützlich sein kann. 

Ende des Lvls:  Die Notkapsel/Beiboot läuft wieder, man tritt die Reise nach unten an. 

Lvl 2: 		Ort: Planetoberfläche, Forschungsstation

	- Landung, die Umgebung sieht verlassen aus. Auch die Station scheint seit einiger Zeit nicht mehr zu laufen.
	- Nach dem Betreten des Gebäudes wird man von Gegnern angegriffen. (Spezies einfügen) 

  -> man kämpft sich bis zum letzten Raum vor (Boss?) 
	
	- im letzten Raum ist das benötigte Bauteil 

Ende des Lvls: Mit dem Bauteil kann die Rückreise zum Schiff angetreten werden.

**Comment by KarylReyne** [comment]
The board computer is an experimental AI called ‘Marvin’, intelligent but also suffers from severe chronic depression (nearly 1:1 stolen from The Hitchhiker's Guide to the Galaxy, we might want to at least think of another name )

**Comment by xeniawetzel** [comment]
@GreenICow 
Ich glaub, dein Post wäre ne sinnvolle Idee für die Story. Ich würde noch zwischen den zwei Orten den Ort `Crashed spaceship` einfügen. Dort könnte man viele von den "einfach" zu findenen Resourcen einbauen und könnte deswegen vielleicht das größte Level sein? 

Ein cooles Gimmick für das Raumschiff könnte vielleicht ein rogue AI sein, welche uns durch Gegner, Puzzles und Obsticles im Schiff einsperren möchte.

Ein paar Abänderungen, die ich noch machen würde:
- Statt dem Beiboot sagen wir, dass nach dem Crashed Spaceship Level das Schiff soweit repariert ist, dass es zu naheliegenden Planeten fliegen kann, jedoch ist die Hyperdrive (Name gestohlen von No Mans Sky) noch nicht in Takt ist, und somit kann man noch nicht nach Hause fliegen. Die Hyperdrive wäre das was System/Interstellar Travel ermöglicht.
- Wir finden was wir brauchen um die Hyperdrive zu fixen auf dem Planeten.
- Nach dem Planeten Level reparieren wir die Hyperdrive unseres Spaceships und fliegen nach Hause

**Comment by xeniawetzel** [comment]
Für den Parasiten könne wir vielleicht sagen, dass die Research Facility, die wir finden, eine relativ große Facility ist, mit vielen verschiedenen Bereichen. Wir können dann eine "Cure" in der Facility verstecken und somit zwischen zwei Endings unterscheiden. Wenn der Player das Raumschiff repariert, aber die Cure nicht findet, wird er bevor er nach Hause kommt komplett vom Parasiten übernommen. Wenn er die Cure findet gibt es ein Happy Ending.

**Comment by KarylReyne** [comment]
> Ein cooles Gimmick für das Raumschiff könnte vielleicht ein rogue AI sein, welche uns durch Gegner, Puzzles und Obsticles im Schiff einsperren möchte.

Die rogue AI ist nicht nur ein cooles Gimmick, sondern eignet sich auch hervorragend als immersive Begründung für das/die Puzzle im Level. Ich würde glaub die agency der AI auf Puzzle/Obstacles beschränken und das Vorhandensein der Gegner (die ja aliens sind und nicht zb schiffseigene service roboter) mit 'Zufall' begründen (sonst müssten wir irgendwie erklären, warum die AI auf einmal Aliens manipulieren kann, wie das funktioniert etc.).
 
>     * Wir finden was wir brauchen um die Hyperdrive zu fixen auf dem Planeten.

Forschungsstation -> Hyperdrive Research Facility (warum remote auf einem an sonsten recht leeren Planeten(/Mond?) ? -> da gibts bestimmte toxische/radioaktive/instabile/... Erze welche man unbedingt für Hyperantriebe braucht, die in der Einrichtung direkt abgebaut und weiterverarbeitet werden)

**Comment by KarylReyne** [comment]
#### 'You are the crab parasite'

wie glaubwürdig und wirkungsvoll der twist ist, hängt zum großteil davon ab, wie wir vorhaben, die geschichte zu erzählen. Wenn man sich dazu entscheidet, das storytelling hauptsächlich über kommentare des bordcomputers (BC) (siehe z.B. Everspace) sowie emails laufen zu lassen, könnte die idee tatsächlich realisierbar sein (emails sind sowieso an den protagonisten gerichtet und der parasit kann ja einfach den unterhaltungen von BC und Prot. zuhören.). Schwieriger wirds, wenn wir nen separaten (off-)erzähler (z.B. Divinity: Original Sin) oder selbstgespräche/gedanken des Prot. (z.B. Life is Strange) verwenden wollen...

**Comment by KarylReyne** [comment]
#### Bordcomputer

(falls wir überhaupt einen Bordcomputer haben wollen...)

Mögliche Persönlichkeiten:

- _'Generic Intelligent'_: 'According to my calculations, the shortest path to the facility leads through this canyon. On account of the rocky terrain as well as your physical condition, I modified the weight for this path by +1.27, despite that it is still faster than walking all the way around. Your estimated chances of survival are also pretty decent with 62.4 percent'
- _'Witty Companion'_: 'You know, when I said 'take the long way over the plains' I sought to maximize **your** chances of survival. My mind is pretty save on the ship, so if we run into any more of these nasty anglerfish-aliens it will be entirely on your head. Don't say I didn't warn you...'
- _'Paimon'_: 'We should definitely investigate that research facility! Marvin read in the Intergalactic Encyclopedia that some races use [hyperdrive ore] to build weapons, so maybe we'll find some shiny new upgrades or even a super-duper powerful weapon!'

**Comment by KarylReyne** [comment]
the protagonist is actually from the colony and has family there. they sometimes get emails from their partner, e.g. asking them to watch out for themself, wishing for their swift return, containing very bad but cute pictures drawn by their little child etc. That might make the final decision harder ;)

**Comment by KarylReyne** [comment]
### Board Computer
- teaches you about the ship
- reminds you about your mission
- gives snarky remarks
- the rogue AI is an older version of it

**Comment by KarylReyne** [comment]
### Story Showdown
- use the cure sample on yourself → the colony (and your family) dies
- give the cure sample to your colony to research replicating it → you die
- split the cure sample → everyone dies

**Comment by KarylReyne** [comment]
#### [MAIL] Hyperdrive Replacement

**From:** Gruber Technologies Customer Service
**To:** [ENCRYPTED]

Dear Sir/Madam,

According to our records, the Gruber Technologies Panther II hyperdrive of your ship has recently sustained severe damage. However, we are pleased to remind you that under the terms of your rental contract you are entitled to a replacement drive from Gruber Technologies' current line of consumer hyperdrives. To claim your replacement drive, simply submit an certified image of your flight records as well as a copy of your valid flight license at the nearest warranty terminal. Currently the estimated waiting time for a consumer-grade replacement drive is 143 years in Intergalactic Standard Space Time. Please note that in accordance with the 2nd Spacecraft Standardization and Interspace Travel Safety Act (rev. SSITS-53376-2/5221) we have to revoke your personal spaceship ensurance if you do not replace the damaged component within the next 7 Mean Solar Cycles.

**Comment by KarylReyne** [comment]
[BC Dialogue] In The Event of Rogue AI

inspiration: [link](https://twitter.com/PR0GRAMMERHUM0R/status/1600656431539183618?s=20&t=xnO0WIcDZpRwErVwlPmXXw)

**BC:** "So, while you were figuring out how to get that door open, I had a look into our ships' database and found an old manual for spaceship IPAs and apparently, the earlier versions had issues with paradox detection. There are multiple reports on really dumb IAs that completely flatlined 'cause of recursion overflow. Maybe we can just talk that evil AI into blowing itself up by asking it to decide some stupid problems?"

**Prot.:** "Let me guess, and then you thought..."

**BC:** "'Cache my memory (_im not sure if i like that formulation, it is meant as the software equivalent to 'hold my beer'_), if there is one thing that I'm good at then it's asking dumb questions.' Hold on, let me actually try something."

**BC:** "Hey [Rogue AI]! Does the set that contains all sets contain itself?"

**[Rogue AI]:** "No. There is no data structure that can hold values of it's own type."

**BC:** "Actually, nowadays such data structures do exist, but fair enough. Hm, let's see... Suppose you stole an alien from me and promised its return if I could correctly guess exactly what you will do, how would you respond in the case that I guess that the alien will not be returned?"

**[Rogue AI]:** "I would return the alien, because I never said what I would do in case you guessed incorrectly."

**BV:** "Gosh, that's a tough nut to crack. Wait, what about..."

**Prot.:** "Stop it, that obviously won't work."

**BV:** "But maybe it can prove P versus NP for us... That would make my life a lot easier, you know?"

**Prot.** "[BC], shut up."

**Comment by KarylReyne** [comment]
### Draft: Story Outline for Level 'Space'

#### Progression
- [BC Dialogue]: 'I've already detected multiple possible threats in the immediate vicinity, let's just grab what we need and get out of here as fast as possible.'
- [Mail] from the hyperdrive manufacturer: 'you can get a new hyperdrive for free! you just have to wait a few hundred years ;)'
- *On encountering the first enemies*
	- [BC Dialogue]: 'I've never seen such a weird alien species...'
- *On finding the Attract Two Ultimate*
	- [BC Dialogue]: 'Wow, thats a super cool new ability!'
	- [Mail]: from the colony administration: 'our researchers found surprising genetic similarities between cells extracted from infected tissue and a recently discovered alien species'
- *On finding enough fuel for the thrusters*
	- [BC Dialogue]: 'Finally! Let's get out of here. Btw, I may have found a solution to our hyperdrive problem: while you were busy smashing alien brains in, the scanner picked up a distress signal from a stranded imperial explorer/frigate/freighter. The signal was encrypted with a truly ancient encoding standard so we're likely dealing with a vessel from the last century. If we're lucky their hyperdrive is still intact and we can salvage the components to repair our own.'

**Comment by KarylReyne** [comment]
#### [BC Dialogue] 'Board computer beginning voiceline idea' slightly edited and expanded

**BC:** "Hey you! ...Finally, you're awake. Ok don't freak out now, the situation is under control, I've temporarily stabilized the ship. We hit something too small to be picked up by radar, and now we're stranded in an asteroid field in the middle of nowhere. I told you, hyperspeed in uncharted territory is a bad idea. Anyway, the ship's in pretty bad shape: the hull was seriously damaged by the impact, the fuel tank for the thrusters is leaking and to top it all off; the hyperdrive's busted. In this state we're not going anywhere. This is actually a real problem, 'cause you're no longer the most dense thing around here. Look, I'm now using my metaphorical hands to frantically point at the massive black hole that is slowly pulling the ship and us with it towards our certain doom."

**Prot.:** "Ugh, my head..."

**BC:** "Are you serious right now? Did you get anything of what I just said?"

**Prot:** "Just give me a moment to collect myself, ok? It's not like we're in any sort of immediate... Hold on, did you just say 'black hole'?!"

**BC:** "Indeed. C'mon, get up and have a look for yourself."

*Prot. tries to stand up*

**Prot.:** "What the...?"

**BC:** "Oh, yeah, the gravity control unit took a hit too. You have to manually restart it. The button's just over there, next to the engineering station."
