### ISSUE TITLE
Level 2 Summary

### ISSUE THREAD

**Issue by xeniawetzel** [Mavodeli/spaceroguelite#86]
**Start of level:**
After the cutscene that explains that we found the abandoned spaceship that holds the cure. We spawn in at the entrance of the level.
We left the inference that the black hole caused and get flooded by e-mails.

**Level layout:**
There is 4 points of interest: 
- Crush Ult Room: Unlocks the Crush Ultimate and disables gravity inside all of the abandoned spaceship. Is needed to access the other two rooms. Has a angler fish boss inside that drops the ult. Is just a bigger version of the angler fish with more damage/health.
- Cure Room: Holds the cure. Consists of two parts. Front part of the room is an "office" with at least a table. Second part is an experiment room. Has at least a chair. The cure is at the end of the room behind a laser puzzle.
- Hyperdrive Room: Holds what is needed to repair the hyperdrive. Consists of two parts. Downstairs with at least a piece of metal. An attic that is blocked off by an attic door. The attic has one laser that is separating the character from the hyperdrive diamond.
- An emergency door is blocking off the player from going to the hyperdrive/cure rooms.

**Puzzles:**
- Crush Ult room: A large button can be pressed to disable all gravity inside the abandoned spaceship. Is needed to fly up to the other rooms.
- Emergency door can be broken open using the crush ultimate to get to the hyperdrive/cure rooms.
- Cure room: The wall that separates the "office" and the experiment room has a large glass window and a door in between. You can either use the attract two ultimate to smash the window with the table and chair or use the crush ultimate to break open the locked door. Inside the experiment room there is multiple lasers in front of the cure that have different patterns at which they turn on/off. Maneuver the cure through the lasers using left/right-click and pick it up.
- Hyperdrive room: The door to the attic is locked. Use crush to break it open or negative charge on the metal plate to fling open the door by holden the metal plate next to the attic door. Once in the attic there is a single laser in front of the hyperdrive diamond. Use the metal plate to hold under the laser and attract the diamond and pick it up. The metal plate is destroyed after about 1-1.5 seconds underneath the laser and respawns downstairs.

![Level Design Level 2](https://user-images.githubusercontent.com/92883462/225302164-24b81931-9bfe-4888-bbfd-b65165295b93.png)

**Comment by xeniawetzel** [comment]
Added anti-gravity button to make it easier for us to implement the level layout.

**Comment by KarylReyne** [comment]
Crush Ult Room: at this point the player only has attract two and negative charge. negative charge doesn't deal damage so attract two is the only ability that can damage the angler fish. for attract two to work we need at least two objects => put a lot of cargo containers + crates in the ult room (which fits nicely into the narrative since the ult room is the cargo hold of the abandoned spaceship :) )
